Fix bug: full_name referenced before assignment
If variable['name'] isn't set, then full_name doesn't get created
on line 104.

If variable has children, then full_name will be referenced
on line 139, and an error will occur if it doesn't exist:

UnboundLocalError: local variable 'full_name' referenced
before assignment